EMarket/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using emarket.Context;
using emarket.Models;
using System.IO;
using emarket.ViewModels;

namespace emarket.Controllers
{
    public class CartController : Controller
    {
        MyContext db = new MyContext();
        // GET: Cart
        public ActionResult ListCart()
        {
            var cart = db.cart.ToList();

            return PartialView(cart);
        }
        public ActionResult DeleteCart(int id)
        {
            var cart = db.cart.SingleOrDefault(c => c.product_id == id);
            db.cart.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index","Product");

        }
    }
}

EMarket/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMarket.Context;
using EMarket.Models;

namespace EMarket.Controllers
{
    public class CartsController : Controller
    {
        private sotreContext db = new sotreContext();

        public ActionResult ListCart()
        {
            var cart = db.carts.ToList();

            return PartialView(cart);
        }
        public ActionResult DeleteCart(int id)
        {
            var cart = db.carts.SingleOrDefault(c => c.id == id);
            db.carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index", "Products");

        }
    }
}

EMarket/Views/Shared/_Footer.cshtml
<head>
    <style>
        h3{
            font-family:Arial;
            color:white;
     
             
        }
    </style>
</head>
<footer style= "bottom:0;position:relative;width:100%;background-color:black"> 


    

    <div class="container">

        <h3> Name : Nour Maher   &nbsp &nbsp&nbsp&nbsp&nbsp&nbsp &nbsp &nbsp &nbsp  Id : 20170602 ,&nbsp &nbsp &nbsp &nbsp    Name : Mina Nasr    &nbsp &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp &nbsp  Id : 20170582</h3>
        <h3> Name : Mariam Awad  &nbsp &nbsp &nbsp&nbsp&nbsp &nbsp &nbsp  Id : 20170517, &nbsp &nbsp &nbsp &nbsp    Name : Mariana Samir&nbsp &nbsp &nbsp&nbsp&nbsp&nbsp &nbsp  Id : 20170513</h3>
        <h3> Name : Malak Mamdouh  &nbsp &nbsp &nbsp &nbspId : 20170557 ,&nbsp &nbsp &nbsp &nbsp    Name : Poula Benjamen&nbsp &nbsp &nbsp &nbsp  Id : 20160112</h3>
    </div>
</footer>
<!-- Footer -->

EMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "products")</li>
                    <li>@Html.ActionLink("categories", "Index", "categories")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    <li> <a onclick="ShowCart()" href="/Carts/ListCart">  GO TO CART LIST </a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer class="navbar-fixed-bottom">
            <hr />
            <p>&copy; @DateTime.Now.Year - E-market </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        var ShowCart = function () {
                var url = "@Url.Action("ListCart","Carts")";
                $("#ListCartModalBody").load(url, function () {
                    $("#CartModal").modal("show");

                })
            }

    </script>
</body>
</html>

EMarket/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Products", "Index", "Product")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

            </ul>
            <ul class="nav navbar-nav navbar-right">

                <li> <a onclick="ShowCart()">  GO TO CART LIST </a></li>

            </ul>
        </div>
    </div>
</div>
<div class="modal fade" id="CartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:bisque; text-align:center;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel" style="font-family:'Times New Roman', Times, serif; font-size:x-large;"> CART LIST </h4>
            </div>
            <div class="modal-body" id="ListCartModalBody">

            </div>

        </div>
    </div>
</div>

<script>
            var ShowCart = function () {
                var url = "@Url.Action("ListCart","Cart")";
                $("#ListCartModalBody").load(url, function () {
                    $("#CartModal").modal("show");

                })
            }

</script>